version: '2.1'

networks:
  pwcalc-net:
    driver: bridge

services:
  pwcalc:
    image: ckevi/pwcalc:2.0-root
    container_name: pwcalc
    restart: unless-stopped
    ports:
        - "3333:3333"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pwcalc-net

