version: '3.3'

networks:
  pwcalc-net:
    driver: bridge

services:
  pwcalc:
    image: ckevi/pwcalc:3.0-root
    container_name: pwcalc
    restart: unless-stopped
    ports:
        - "3333:3333"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pwcalc-net

  pwcalc-runner:
    image: ckevi/pwcalc-runner:2.0
    container_name: pwcalc_runner
    restart: unless-stopped
    expose:
        - "1099"
    networks:
        - pwcalc-net
